// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

export interface Kanban { todo: Array<Task>, in_progress: Array<Task>, done: Array<Task>, }