// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Todo } from "./Todo";

export interface Memo { todo: Array<Todo>, in_progress: Array<Todo>, done: Array<Todo>, }